apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: predictive-autoscaling

resources:
  - namespace.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - webapp-deployment.yaml
  - prometheus-rbac.yaml
  - prometheus-configmap.yaml
  - prometheus-deployment.yaml
  - cadvisor-daemonset.yaml
  - grafana-deployment.yaml
  - load-generator-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: predictive-autoscaling
  app.kubernetes.io/managed-by: kustomize

images:
  - name: metrics-webapp
    newTag: latest
  - name: load-generator
    newTag: latest
